import { Toaster } from "sonner";
import "./globals.css";
import { Inter } from "next/font/google";
import { UserProvider } from "../contextApi/UserContext";
import Navbar from "../components/ui/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
      <body className={inter.className}>
          <Navbar/>
          {children}
          <Toaster />
      </body>
      </UserProvider>
    </html>
  );
}
